trigger:
  branches:
    include:
    - main
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  ci_feed: https://pkgs.dev.azure.com/andrewarnott/OSS/_packaging/PublicCI/nuget/v3/index.json

jobs:
- template: azure-pipelines/build.yml
