<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="AssemblyRefScanner">
      <HintPath>$(RepoRootPath)bin\AssemblyRefScanner\$(Configuration)\net8.0\AssemblyRefScanner.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="xunit.v3.assert.aot" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
    <PackageReference Include="xunit.v3.assert" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AssemblyRefScanner" />
    <Using Include="Xunit" />
    <Using Include="TUnit.Core" />
  </ItemGroup>

</Project>
