steps:
- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/deployables-Linux/*.nupkg -s $(ci_feed) -k azdo --skip-duplicate
  displayName: Push nuget package to CI
  condition: and(succeeded(), ne(variables['ci_feed'], ''), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
