parameters:
  includeMacOS:

steps:
- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Pipeline.Workspace)' -OutputFile coveragereport/merged.cobertura.xml -Format Cobertura -Verbose
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@2
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    summaryFileLocation: coveragereport/merged.cobertura.xml
    failIfCoverageEmpty: true
