trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  pipelines:
  - pipeline: CI
    source: AArnott.AssemblyRefScanner
    trigger:
      tags:
      - auto-release

variables:
- group: Publishing secrets

jobs:
- job: release
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: none
  - powershell: Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
    displayName: Set pipeline name
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: sdk
      version: 6.x
  - task: GitHubRelease@1
    displayName: GitHub release (create)
    inputs:
      gitHubConnection: github.com_AArnott_OAuth
      repositoryName: $(Build.Repository.Name)
      target: $(resources.pipeline.CI.sourceCommit)
      tagSource: userSpecifiedTag
      tag: v$(resources.pipeline.CI.runName)
      title: v$(resources.pipeline.CI.runName)
      isDraft: true # After running this step, visit the new draft release, edit, and publish.
      changeLogCompareToRelease: lastNonDraftRelease
      changeLogType: issueBased
      changeLogLabels: |
        [
          { "label" : "bug", "displayName" : "Fixes", "state" : "closed" },
          { "label" : "enhancement", "displayName": "Enhancements", "state" : "closed" }
        ]
  - download: CI
    artifact: deployables-Linux
    displayName: Download deployables-Linux artifact
    patterns: 'deployables-Linux/*'
  - script: dotnet nuget push $(Pipeline.Workspace)/CI/deployables-Linux/*.nupkg -s https://api.nuget.org/v3/index.json --api-key $(NuGetOrgApiKey) --skip-duplicate
    displayName: Push nuget packages
    condition: and(succeeded(), ne(variables['NuGetOrgApiKey'], ''))
